indexing on nd-array
========

       =========================
             indexing=:-
       =========================
    if we want to access a single element from a array then the must go for indexing.

               ===============================================
                Accessing single element from 1D-Array:-
               ===============================================
   ----------------------------------
    syntax=    array_name[index]
   ----------------------------------
    => here index value is either positive or negative.
 ---------
   EX=
 ---------

In [2]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
print(a)

[1 2 3 4 5 6 7 8]


In [4]:
#accessing 5 from a.
print(a[4])

5


In [7]:
#accessing 2 by using negative indexing.
print(a[-7])

2


               ===============================================
                Accessing single element from 2D-Array:-
               ===============================================
   ----------------------------------
    syntax=    array_name[row index,column index ]
   ----------------------------------
    => here index of row and columns are is either positive or negative.
 ---------
   EX=
 ---------

In [8]:
a=np.array([10,20,30,40,50,60,70,80,90])
print(a.ndim)
print(a)

1
[10 20 30 40 50 60 70 80 90]


In [11]:
b=a.reshape(3,3)
print(b)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [13]:
#accesing 40 from b array.
print(b[1,0])

40


In [15]:
#accesing 40 from b array.
print(b[1][0])

40


In [17]:
#accesing 40 by using negative indexing.
print(b[-2,-3])

40


In [21]:
#accesing 20 by using positive and negative indexing.
print(b[0,-2])

20


In [22]:
b.ndim

2

          ===============================================
            Accessing single element from 3D-Array:-
           ===============================================
       ------------------------------------------------------------------------
        syntax=    array_name[index of matrix,row index, column index ]
       ------------------------------------------------------------------------

=> here index of row and columns are is either positive or negative.

In [24]:
a=np.array([28,29,23,40,61,38,91,37])
a.ndim

1

In [28]:
b=a.reshape(2,2,2)
print(b)
print(b.ndim)

[[[28 29]
  [23 40]]

 [[61 38]
  [91 37]]]
3


SLICING:=
==========

       =====================
        1D Array slicing:=
       =====================
       => if we want range of elements from array then we go for slicing.
       ------------------------------------------------
           syntax:- array_name(begin:end:step)
       ------------------------------------------------
      => here the begin,end,step values are positive or negative.

In [2]:
import numpy as np
a=np.array([12,82,34,98,92,54,42,143,963,921,982,4])
print(a)
print(a.ndim)

[ 12  82  34  98  92  54  42 143 963 921 982   4]
1


In [5]:
#accessing from 12 to 143 with positive indexing.
print(a[0:8])

[ 12  82  34  98  92  54  42 143]


In [24]:
#accessing from 12 to 143 with negative indexing.
print(a[-12:-4])

[ 12  82  34  98  92  54  42 143]


In [27]:
#accessing only 82,98,54,143,921,4
print(a[1::2])

[ 82  98  54 143 921   4]


In [28]:
#accessing only 4,921,143,54,98,82
print(a[-1:-12:-2])

[  4 921 143  54  98  82]


       =====================
        2D Array slicing:=
       =====================
       => if we want range of elements from array then we go for slicing.
       ------------------------------------------------
           syntax:- array_name(begin:end:step for row and begin:end:step for column)
       ------------------------------------------------
      => here the begin,end,step values are positive and negative.

In [30]:
import numpy as np
a=np.array([16,8,4,6,0,52,986,432,987])
print(a)

[ 16   8   4   6   0  52 986 432 987]


In [33]:
b=a.reshape(3,3)
print(b)

[[ 16   8   4]
 [  6   0  52]
 [986 432 987]]


In [36]:
#accessing from 0 to 52 and 432 to 987
print(b[1:3,1:3])

[[  0  52]
 [432 987]]


In [45]:
#accesing   0  52 and 432 987 by using negative indexing.
print(b[:,:])

[[ 16   8   4]
 [  6   0  52]
 [986 432 987]]


In [49]:
#accessing 16,4..6 and 52
print(b[:2,::2])

[[16  4]
 [ 6 52]]


In [62]:
print(b[-3:-1,-3:-1])

[[16  8]
 [ 6  0]]


In [63]:
print(b[-4:,-2:])

[[  8   4]
 [  0  52]
 [432 987]]


advanced slicing:=
============

In [73]:
#accessing identity elements from b array.
import numpy as np
a=np.array([16,8,4,6,0,52,986,432,987])
b=a.reshape(3,3)
print(b[(0,1,2),(0,1,2)])

[ 16   0 987]


In [80]:
#accessing randomly from b.
print(b)
print("="*35)
print("random elements=",b[(0,1,1,2),(1,0,2,1)])
print("="*35)

[[ 16   8   4]
 [  6   0  52]
 [986 432 987]]
random elements= [  8   6  52 432]


       =====================
        3D Array slicing:=
       =====================
       => if we want range of elements from array then we go for slicing.
       -----------------------------------------------------------------------------------------------------
           syntax:- array_name(matrix number slicing,begin:end:step for row and begin:end:step for column)
       -----------------------------------------------------------------------------------------------------
      => here the begin,end,step values are positive or negative.

In [94]:
a=np.array([10,20,30,40,50,60,70,70,80,90,12,81])
b=a.reshape(3,2,2)
print(b)
print("="*35)
print(b[(0,1,2),(1,0,1),(1,1,0)])
print("="*35)
print(b[:,1:,0:])
print("="*35)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 70]]

 [[80 90]
  [12 81]]]
[40 60 12]
[[[30 40]]

 [[70 70]]

 [[12 81]]]


In [95]:
print(b[:,0:,1])

[[20 40]
 [60 70]
 [90 81]]


In [98]:
#accessing elements randomly from b.
print(b[(0,1),(0,1),(0,1)])

[10 70]


In [100]:
print(b[0,1,1])

40


In [101]:
print(b[(2,1,0)])

12
