                                           ================================
                                                       ndarray
                                           ================================
        => ndarray is one of pre-defined class in numpy module.
        => an object of ndarray is used to store the data in numpy programming.
        => we have 7 ways to create object of ndarray of numpy module.
                1.array()
                2.arange()
                3.zeros()
                4.ones()
                5.full()
                6.eye()
                7.identit()
array():-
========
     =>it converts iterable object into ndarray object type.
     =====================================================
        SYNTAX:- varname=nd.array(iterable object,dtype)
     =====================================================
     => here varname is an object of <class 'numpy.ndarray'>
     => here dtype represents data type of c lang---> int32,int64,float32....etc.
     => by this we can creat n-dimensions of array.

In [16]:
import numpy as nd
l1=[10,20,30]
array1=nd.array(l1,dtype=int)
print("type of l1=",type(l1))
print("numpy array=",array1)
print("type of array1=",type(array1))
print("datatype of ndarray=",array1.dtype)
print("dimension of array1=",array1.ndim)

type of l1= <class 'list'>
numpy array= [10 20 30]
type of array1= <class 'numpy.ndarray'>
datatype of ndarray= int32
dimension of array1= 1


In [11]:
print("address of 1st element of l1=",id(l1[0]))
print("address of 2nd element of l1=",id(l1[1]))
print("address of 3rd element of l1=",id(l1[2]))
print("adress of 1st elemnt of array1=",id(array1[0]))
print("adress of 2nd elemnt of array1=",id(array1[1]))
print("adress of 3rd elemnt of array1=",id(array1[2]))

address of 1st element of l1= 140717709235272
address of 2nd element of l1= 140717709235592
address of 3rd element of l1= 140717709235912
adress of 1st elemnt of array1= 1589824589872
adress of 2nd elemnt of array1= 1589824589872
adress of 3rd elemnt of array1= 1589824589872


arange():-
============
    * it is used to create object of ndarray.
    =====================================================
      SYNTAX:- varname=nd.arange(start,end,step,dtype)
    =====================================================
    => by this function we creat only 1-dimensional arrays only.
    => so we can convert the 1-dimensional array to any required dimensional array we use reshape() function.

In [3]:
import numpy as nd
a=nd.arange(0,10)
print(a,type(a))
print("shape of a=",a.shape) #returns total number of elements in array
print("dimension of a=",a.ndim) #returns number of dimensions of array

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
shape of a= (10,)
dimension of a= 1


In [5]:
b=a.reshape(2,5) #here 2 is no.of rows and 5 is no.of colmns
print("converted array=",b)

converted array= [[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
import numpy as nd
c=nd.arange(20,44,2)
print(c)

[20 22 24 26 28 30 32 34 36 38 40 42]


In [8]:
d=c.reshape(3,2,2) #here 3 is no.of matrixes,2 is no.of rows and 2 is no.of colmns
print(d)

[[[20 22]
  [24 26]]

 [[28 30]
  [32 34]]

 [[36 38]
  [40 42]]]


3.ZEROS():-
===========
    =>Is used to create a matrix with all zeros.
    =====================================================
          SYNTAX:- varname=nd.zeros(shape,dtype)
    =====================================================
    => here dtype is optional,by default it takes float
    => here shape is 1-dimensional or 2-dimensional.

In [14]:
import numpy as nd
a=nd.zeros(4)
print(a)
print("shape=",a.shape)

[0. 0. 0. 0.]
shape= (4,)


In [16]:
import numpy as nd
b=nd.zeros((3,3),dtype=int)
print(b)
print("shape=",b.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
shape= (3, 3)


4.Ones():-
=============
    =>Is used to create a matrix with all ones.
    =====================================================
      SYNTAX:- varname=nd.ones(shape,dtype)
    =====================================================
    => here dtype is optional,by default it takes float
    => here shape is 1-dimensional or 2-dimensional.

In [21]:
import numpy as nd
a=nd.ones((4,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
print("datatype of a=",a.dtype)
print("shape=",a.shape)

datatype of a= float64
shape= (4, 4)


5.full():-
===========
    => This is used to create a matrix with user specified value.
    =====================================================
      SYNTAX:- varname=nd.full(shape,full_value,dtype)
    =====================================================
    =>here full_value is user-defined

In [23]:
a=nd.full(4,9)
print(a)

[9 9 9 9]


In [26]:
b=nd.full((3,3),25,dtype=int)
print(b)
print("shape of b=",b.shape)
print("dimension=",b.ndim)

[[25 25 25]
 [25 25 25]
 [25 25 25]]
shape of b= (3, 3)
dimension= 2


6.EYE():-
==========
        ==========================================================
                  SYNTAX:-nd.eye(N,M=None,K=0,dtype)
        ==========================================================
        => here N represents no.of rows.
        => M represents no.of columns,we can't mention M value default it takes N value considered as M value.
        => if we specify M value then it gives (N by M) matrix and remaining values filled with zero's.
        =>here K represents principal diagonal.
               * k=0 then it filled principle diagonal and it is default
               * K=-1,-2,-3... then it consider below principle diagonal.
               * k=1,2,3... then it is consider as above priciple diagonal.

In [28]:
a=nd.eye(3,M=None,k=0,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [30]:
b=nd.eye(3,4,k=0)
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [33]:
c=nd.eye(8,k=0,dtype=int)
print(c)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


In [35]:
c=nd.eye(8,k=-1,dtype=int)
print(c)

[[0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]]


In [37]:
c=nd.eye(8,k=3,dtype=int)
print(c)

[[0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


7.IDENTITY():-
=============
    => This function generates only square identity matrix.
    =============================================
         SYNTAX:nd.identity(shape,dtype)
    =============================================
    => here shape is specifies like n by n matrix.

In [38]:
a=nd.identity(6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [39]:
b=nd.identity(3,4,dtype=int)
print(b)

TypeError: identity() got multiple values for argument 'dtype'

In [40]:
b=nd.identity(8,dtype=int)
print(b)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]
